server:
  port: 5050
#  servlet:
#    session:
#      timeout: 10m

spring:
  datasource:
    url: jdbc:h2:~/shopping_backend
    platform: h2
    username: sa
    password:
    initialization-mode: always
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show-sql: true
        use_sql_comments: true
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 60000

##spring.servlet.multipart.max-file-size=128KB
##spring.servlet.multipart.max-request-size=128KB